DROP TABLE IF EXISTS Theater;
DROP TABLE IF EXISTS Screen_movies;
DROP TABLE IF EXISTS Movie;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Screen;
DROP TABLE IF EXISTS Reserve;
DROP TABLE IF EXISTS New_Reserve;

CREATE TABLE Theater (
  name VARCHAR(250) PRIMARY KEY,
  location  VARCHAR(250) NOT NULL,
  tel VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL
);